// Local-only UI fixtures. Never included in the installable component.
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../plugin-packages/yuketang-notice');
const manifest=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8'));
const image='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200"><rect width="400" height="200" fill="#ddf1e4"/><text x="40" y="110" fill="#226746" font-size="24">课程通知 · 示例配图</text></svg>');
const qr='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="210" height="210"><rect width="210" height="210" fill="white"/><path d="M20 20h60v60H20zM130 20h60v60h-60zM20 130h60v60H20zM110 110h20v20h20v40h40v20h-80z" fill="black"/></svg>');
const host={notifyNew:true,dueReminderHours:24,syncIntervalMinutes:60,showInSidebar:true,addToSchedule:false,feed:{defaultView:'month',dateSource:'automatic',includeCompleted:true,includeReadNotices:true,historyDays:0,includedTypes:null},schedule:{includedTypes:null,includeCompleted:false,includeReadNotices:true,historyDays:0,defaultStartTime:'09:00',durationMinutes:30,showTypeInTitle:true,useTypeColors:true,typeRules:{}}};
const items=[{id:'notice-1',type:'announcement',kind:'notice',title:'下周课程安排调整通知',course:'计算机网络 · 张老师',publishAt:Date.parse('2026-10-03T10:00:00+08:00'),content:'下周一的课程调整至信息楼 302 教室。\n请大家提前安排好时间，准时到课。',images:[{url:image,name:'课程安排示例'}],attachments:[{url:'https://example.invalid/课程安排.pdf',name:'课程安排.pdf'}]},{id:'task-1',type:'homework',kind:'task',title:'第三章 · 网络层课后练习',course:'计算机网络',dueAt:Date.parse('2026-10-03T23:00:00+08:00'),done:false},{id:'exam-1',type:'exam',kind:'task',title:'阶段测验',course:'高等数学',startAt:Date.parse('2026-10-12T09:00:00+08:00'),dueAt:Date.parse('2026-10-12T10:00:00+08:00')},{id:'task-2',type:'homework',kind:'task',title:'第二章 · 物理层练习',course:'计算机网络',dueAt:Date.parse('2026-10-15T23:00:00+08:00'),done:true},{id:'notice-2',type:'announcement',kind:'notice',title:'实验课分组名单',course:'计算机网络',publishAt:Date.parse('2026-09-29T09:00:00+08:00'),content:'分组名单见附件。',done:true},{id:'old-1',type:'announcement',kind:'notice',title:'上学期课程总结',course:'大学物理',historical:true,publishAt:Date.parse('2026-09-01T10:00:00+08:00')}];
function script(params){const data={host,loginState:params.get('state')||'logged_in',account:{id:'fixture',name:'林同学',school:'课简演示数据'},settings:{site:'changjiang.yuketang.cn'},items,lastSyncAt:Date.parse('2026-10-03T09:00:00+08:00')};return `<script>
let fixture=${JSON.stringify({manifest,data,context:{timeZone:'Asia/Shanghai',nowMillis:Date.parse('2026-10-03T12:00:00+08:00')}})};
const listeners=new Set();window.calls=[];window.push=()=>listeners.forEach(f=>f(fixture));
window.CurSimpleComponent={get state(){return fixture;},subscribe(fn){listeners.add(fn);fn(fixture);return()=>listeners.delete(fn)},async request(command,payload={}){window.calls.push(command);if(command==='settings.update'){Object.assign(fixture.data.settings,payload);push();return fixture.data;}if(command==='host.update'){fixture.data.host=payload;push();return fixture.data;}if(command==='web.cookie')return 'fixture-cookie';if(command==='qr.encode')return ${JSON.stringify(qr)};if(command==='login.check'){if(new URLSearchParams(location.search).get('result')==='session-error')throw new Error('账号校验超时，请重新检查登录结果');fixture.data.loginState='logged_in';push();return fixture.data;}if(command==='logout'){fixture.data.loginState='logged_out';fixture.data.items=[];push();return fixture.data;}if(command==='ui.login')location.href='login.html?state=never';if(command==='ui.settings')location.href='settings.html'+location.search;if(command==='ui.feed')location.href='feed.html?state='+fixture.data.loginState;if(command==='sync')return {count:fixture.data.items.length};
if(command==='media.download'){const e={id:'dl-'+(window.__dl.length+1),name:decodeURIComponent(payload.url.split('/').pop()),url:payload.url,mime:'application/pdf',size:183400,savedAt:Date.now()};window.__dl=window.__dl.filter(x=>x.url!==e.url).concat(e);return e;}
if(command==='media.downloads')return window.__dl;
if(command==='media.delete'){const n=window.__dl.length;window.__dl=window.__dl.filter(x=>x.id!==payload.id);return window.__dl.length<n;}
if(command==='media.saveImage')return true;
return true;}};
window.__dl=new URLSearchParams(location.search).get('dl')==='1'?[{id:'dl-0',name:'课程安排.pdf',url:'https://example.invalid/课程安排.pdf',mime:'application/pdf',size:183400,savedAt:Date.parse('2026-10-03T10:30:00+08:00')}]:[];
window.TencentCaptcha=class{constructor(id,cb){this.cb=cb;}show(){this.cb({ret:0,ticket:'fixture',randstr:'fixture'});}};
// Simulate QR events; ws-success also emits authenticated state.
const WS_OK=new URLSearchParams(location.search).get('result')!=='ws-fail';
window.WebSocket=class{constructor(url){this.url=url;this.readyState=0;setTimeout(()=>{if(!WS_OK){this.onerror?.(new Event('error'));return;}this.readyState=1;this.onopen?.();setTimeout(()=>{this.onmessage?.({data:JSON.stringify({op:'requestlogin',loginid:'fixture',expire_seconds:60,ticket:'https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=fixture',qrcode:'http://weixin.qq.com/q/fixture'})});if(new URLSearchParams(location.search).get('result')==='ws-success'){setTimeout(()=>this.onmessage?.({data:JSON.stringify({op:'loginsuccess',UserID:1,Auth:'fixture-auth'})}),600);}},120);},80);}send(){}close(){this.readyState=3;this.onclose?.({code:1000});}};
window.fetch=async(url,init={})=>{const p=new URL(url,location.href).pathname;let value={success:true,status_code:200};if(p.endsWith('verify_pwd_login/')){const code=JSON.parse(init.body).pwd;if(code==='000000')value={success:false,msg:'验证码不正确或已过期'};}
if(p.endsWith('app-web-pre-info'))value={code:0,data:{qrContent:'https://mp.weixin.qq.com/fixture',token:'fixture',expire_seconds:30}};
if(p.endsWith('app-web-login'))return new Promise((resolve,reject)=>{const done=()=>reject(new DOMException('cancelled','AbortError'));init.signal.addEventListener('abort',done);});
return {ok:true,status:200,json:async()=>value};};
window.__errors=[];window.addEventListener('error',e=>__errors.push(e.message));window.addEventListener('unhandledrejection',e=>__errors.push(String(e.reason)));
</script>`;}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1');const name=path.basename(u.pathname==='/'?'feed.html':u.pathname);if(!/^[\w.-]+$/.test(name))throw Error();let body=await fs.readFile(path.join(root,'ui',name));const type=name.endsWith('.html')?'text/html':name.endsWith('.js')?'application/javascript':'text/css';if(name.endsWith('.html'))body=body.toString().replace('<head>','<head>'+script(u.searchParams));res.writeHead(200,{'Content-Type':type+'; charset=utf-8','Cache-Control':'no-store'});res.end(body);}catch{res.writeHead(404);res.end();}}).listen(8766,'127.0.0.1',()=>console.log('Component fixture preview: http://127.0.0.1:8766'));
